create table QUESTION(
	QUESTION_ID VARCHAR2(2),
	QUESTION_TEXT VARCHAR2(200),
	OPTION_A VARCHAR2(50),
	OPTION_B VARCHAR2(50),
	OPTION_C VARCHAR2(50),
	OPTION_D VARCHAR2(50),
	OPTION_CORRECT VARCHAR2(1),
	CURRENT BOOLEAN	
);

create table RESPONSE(
	QUESTION_ID VARCHAR2(2),
	EMPLOYEE_EMAIL VARCHAR2(100),
	OPTION VARCHAR2(50),
	TIME_STAMP TIMESTAMP
);